CREATE DATABASE IF NOT EXISTS escola;
USE escola;

CREATE TABLE IF NOT EXISTS alunos (
   Id INT AUTO_INCREMENT PRIMARY KEY,
   Nome INT NOT NULL, 
   Idade INT NOT NULL,
   Curso VARCHAR(50) NOT NULL
 );